### PR TITLE
Fixes #28

### LINKED ISSUE #28: Issues with Wearable Backpacks
Equipping the backpack in your chestplate slot disables wings and makes them not work

### PR DESCRIPTION
**Pull request by Laike-Endaril**
Somewhat rough, but I tried to match the existing code style and project layout as best I could.

The check itself could be made more efficient, but I was unsure where to put the conversion code and datastructure it would require.  That said, it is working as intended, and I don't expect any noticeable performance impact unless a user inputs a horrendous number of entries into the array.

### CODE REVIEW

File: src/main/java/me/paulf/wings/server/config/ArmorBlacklistConfig.java [hunk 1]
```diff
@@ -0,0 +1,12 @@
+package me.paulf.wings.server.config;
+
+import me.paulf.wings.WingsMod;
+import net.minecraftforge.common.config.Config;
+
+@Config(modid = WingsMod.ID, name = WingsMod.ID + "/armorblacklist", category = "armorblacklist")
+public final class ArmorBlacklistConfig {
+	@Config.LangKey("config.wings.armorblacklist")
+	public static String[] disallowedItems = new String[] {
```
Comment (pau101) [inline src/main/java/me/paulf/wings/server/config/ArmorBlacklistConfig.java]: I would call this configuration `wearObstructions`

File: src/main/resources/assets/wings/lang/en_us.lang [hunk 2]
```diff
@@ -76,3 +76,6 @@ config.wings.items.settings.requiredLandSatiation.tooltip=The satiety level requ
 config.wings.items.settings.landingExertion.tooltip=The exertion amount for landing
 config.wings.items.settings.durability=Item Durability
 config.wings.items.settings.durability.tooltip=Infinite durability specified by 0
+
+config.wings.equipmentBlacklist=Armor Blacklist
+config.wings.equipmentBlacklist.tooltip=Wings will be disabled if you have one of these equipped
```
Comment (pau101) [inline src/main/resources/assets/wings/lang/en_us.lang]:
```suggestion
config.wings.wearObstructions.tooltip=Customize which items when worn in the chest slot obstruct wings in the baubles body slot.
```

**Comment by Laike-Endaril** [comment]
This was not quite ready yet, found a couple things to fix after the merge.  For some reason, my fork still says 9 commits ahead (the total number of commits in my branch), instead of the remainder after the merge.
